services:
  consumer:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: consumer
    networks:
      - network1
    volumes:
      - ./app:/consumer/app

networks:
  network1:
    name: mynetwork
    driver: bridge


