services:
  broker-1:
    image: apache/kafka:4.2.0
    container_name: broker-1
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:29092,EXTERNAL://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - network1

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    networks:
      - network1
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker-1:29092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - broker-1 

networks:
  network1:
    name: mynetwork
    driver: bridge